services:
#web
    web_nginx:
        build:
            context: ./infra/web
            args:
                BUILD_ARGUMENT_ENV: dev
            dockerfile: ./nginx/Dockerfile
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web:/var/www/html:ro,cached
            - ./infra/web/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - web_server
        networks:
            - symfony

    web_server:
        environment:
            GEMINI_API_KEY: 'AIzaSyBhjR2N3cFdwdiW7MmD8fUVWIe0i_vJRck'
        build:
            context: ./infra/web
            dockerfile: ./php/Dockerfile
        volumes:
            - ./web:/var/www/html:cached
            - ./infra/web/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./infra/web/php/config/php.ini:/usr/local/etc/php/php.ini
            - ./infra/web/php/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            - web_mysql
        networks:
            - symfony
        expose:
            - "9000"
            - "9003"

    web_mysql:
        image: mysql
        platform: linux/x86_64
        command: --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1} --sql_mode=${SQL_MODE:-"ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"}
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql:delegated
        networks:
            - symfony

    web_myadmin:
        image: phpmyadmin/phpmyadmin:5
        environment:
            PMA_HOST: web_mysql
        ports:
            - "8080:80"
        depends_on:
            - web_mysql
        networks:
            - symfony
        volumes:
            - db_admin_data:/var/www/html


    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db
        networks:
            - symfony
    mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongo
            - MONGO_INITDB_ROOT_USERNAME='admin'
            - MONGO_INITDB_ROOT_PASSWORD='pass'
        networks:
            - symfony
volumes:
    db_admin_data:
    mysql:
    mysql_user:
    esdata:
    mongodb_data:
    mongo-data:

networks:
    symfony:
        name: symfony
