<?php

namespace ContainerX7nDeas;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BJEjOXt.App\Controller\AiController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BJEjOXt.App\\Controller\\AiController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assistant' => ['privates', 'App\\Ai\\Service\\MyAssistant', 'getMyAssistantService', true],
        ], [
            'assistant' => 'App\\Ai\\Service\\MyAssistant',
        ]))->withContext('App\\Controller\\AiController::index()', $container);
    }
}
