<?php

namespace ContainerX7nDeas;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAi_Platform_Contract_GoogleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ai.platform.contract.google' shared service.
     *
     * @return \Symfony\AI\Platform\Contract
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ai-platform/src/Contract.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ai-platform/src/Bridge/Gemini/Contract/GeminiContract.php';

        return $container->privates['ai.platform.contract.google'] = \Symfony\AI\Platform\Bridge\Gemini\Contract\GeminiContract::create();
    }
}
