<?php

namespace ContainerX7nDeas;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAi_Security_IsGrantedAttributeListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ai.security.is_granted_attribute_listener' shared service.
     *
     * @return \Symfony\AI\AiBundle\Security\EventListener\IsGrantedToolAttributeListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ai-bundle/src/Security/EventListener/IsGrantedToolAttributeListener.php';

        $a = ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container));

        if (isset($container->privates['ai.security.is_granted_attribute_listener'])) {
            return $container->privates['ai.security.is_granted_attribute_listener'];
        }

        return $container->privates['ai.security.is_granted_attribute_listener'] = new \Symfony\AI\AiBundle\Security\EventListener\IsGrantedToolAttributeListener($a, NULL);
    }
}
