<?php

namespace ContainerX7nDeas;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAi_TraceablePlatform_GeminiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ai.traceable_platform.gemini' shared service.
     *
     * @return \Symfony\AI\AiBundle\Profiler\TraceablePlatform
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ai-platform/src/PlatformInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ai-bundle/src/Profiler/TraceablePlatform.php';

        return $container->privates['ai.traceable_platform.gemini'] = new \Symfony\AI\AiBundle\Profiler\TraceablePlatform(($container->privates['ai.traceable_platform.gemini.inner'] ?? $container->load('getAi_TraceablePlatform_Gemini_InnerService')));
    }
}
