<?php

namespace ContainerX7nDeas;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerpApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Symfony\AI\Agent\Toolbox\Tool\SerpApi' shared autowired service.
     *
     * @return \Symfony\AI\Agent\Toolbox\Tool\SerpApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ai-agent/src/Toolbox/Tool/SerpApi.php';

        return $container->privates['Symfony\\AI\\Agent\\Toolbox\\Tool\\SerpApi'] = new \Symfony\AI\Agent\Toolbox\Tool\SerpApi(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('SERP_API_KEY'));
    }
}
