<?php

namespace ContainerX7nDeas;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeInfo_Resolver_StringService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'type_info.resolver.string' shared service.
     *
     * @return \Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php';

        return $container->privates['type_info.resolver.string'] = new \Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver();
    }
}
