<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7nDeas\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7nDeas/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7nDeas.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7nDeas\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX7nDeas\App_KernelDevDebugContainer([
    'container.build_hash' => 'X7nDeas',
    'container.build_id' => 'b0fd315b',
    'container.build_time' => 1756681491,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7nDeas');
